sudo: required
services:
- docker
env:
  global:
  - POSTGRES_URI="user=pguser password=pguser dbname=tv-api host=tv_api_postgres sslmode=disable"
  - secure: JjksNFPBF3oDF+rXYN1jtr+GGnYxg4D/CWWWh1UfbXEX7+KHpmnUP3OqlI1+PpuZzfBrljHNZ2qPTIQFY5/TO/H2Q6vtPonKI/Sb2RgqXZu4CLaEsUaCt14ebqrhdb5eWrSF+TBA+CB8ufWRjB89NXzPuNk3OsdoU8qk9vXvrAD+5I/QskrTXJmM30dTLWdmp9hpij8vx/l37P1kClsPCCDnqbZp2nJ1yzTHFmAh7KGXN+qkxpWp1wTczJrXOU+vMotj4leTdqJqLwNL0IwtfpCsZ/HXO2ygfjdJ4N08nyPrMI40UZIck2JXAX0dQWdgOdI5Vp03Cv8/K2vH/SIQtkd6FmiUU7rvZtAX6RqioUTdu3UpFdHAiQynvUhjv0oiPkxmVP19s7afeipwECnOYySB116nehintJD5iltTT2/LYiIjtbxym5czVlbRJIxnqaLbxw9ef/jQD51G+jmeyP5+FfqB/txdmHFsvTRvtwUPOpublZwOpyiQXxCUKAOi5l6w7PnWKQXuVmtPE9aI/XtjygNpEll+l/eiw38hOJ5oeu4DYNZCLcqcxObIftsciTF00DD1XFd/ZxtQjzggdLNKyGEqOnjSP1Io+H9lXVuwseH/fj/D4NujNyphx8JlURt82CpWcJqavBW9DnM6/PHbe41LZ8IQF3A6U9XeUgI=
install:
- cp config/api-common.env config/api.env
- cp config/database-common.env config/database.env
- docker-compose build
- docker-compose up -d
script:
- until docker-compose exec database psql "$POSTGRES_URI" -c "select 1" > /dev/null
  2>&1; do sleep 2; done
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/ml-tv/tv-api && make
  migration"
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/ml-tv/tv-api/src &&
  go test ./..."
deploy:
- provider: script
  on: staging
  skip_cleanup: true
  script: ./deploy_staging.sh
