sudo: required
services:
- docker
env:
  global:
  - POSTGRES_URI="user=pguser password=pguser dbname=tv-api host=tv_api_postgres sslmode=disable"
  - secure: TbSTsWZY0wkV558W0q6PSQ4H08/axExLx1fOuOGwqOscfMnawJxfHAXj8SxvkHPQhhdG4p8cPymQ4Pt+U6kGYnk+dz1T3E6yE0Ogh0GvtMEBmSpPAC5yo32NbHn+VQwsSzTIrqkz576xKhXw/5t+mNx+HvyLfn1/xFvULqVRCJaLZIp0mS/RVUsLSEwBKTVvzHW4i4hB/Y8xGKoPUmMFhn+mWEAbxj4KL5O34JDtMMAa3gAdTXCy+5NY27CyoUTsQN7C0pfrhI2V84G9FNDH0MdgJWgvIQLKavRHYPdqK+Rv4u5zemlZ4ctJ4X9XvE+prWICWgFNSdsauvY7maN/XEGm/D8cEekUBEm9f+gTrwyMsGThf/qSW7/PVKrZvihCn//XxpIkkjJIOVfm4GFJ6If0c9Vx+doPtotOFNDnOJWZ3gZSQGaRa9ciypcVAKjgvDrqp2MEwr25sX2lTfcVgXSH0BZl9uTGOrk+OKV7+lu+04bJL/xK6e3ds12UElK+AWDdewDsv64HdkGOtD8mFngpOyKKr7HldXbGCQDe00pAEYgqB4VLnEdmOrhUYSKg7yLpjbqYOuRCZrPibkxSehIJvG7OCwZkG6tuar8cuUsn4KucLo9Su98/8LmmtlIc4DBvBHkwxls/BvVXrGoBvwShSdBGGe5e/4y3Krp6QMQ=
  - secure: PN+wa1ecZnOVhI8Tk9d824f4gK6OyDEZwepKHKEVXvLvwD3BzsORt4IOUKEzwd6yDq3yFoM9XlRqc0Jupof2l3ad3AV83O7kMCfkYZ1doeNdsrdWg5EcGn8ak6IaGAHojbIfxJ5MXNvHHxuX3jBAuSXyKEwg3WIPYrMkJdv+NWMfqnchTwbw4HdP1praRyM1Kx/wzWzVlv7CLAu0dvKKl7X4QA4D9A96gokKklsqA78D/BB2UoX+dsPUnAXr+/6JnV6PiXIlPB6TnikBJDA6Z0jA2FAZYIqqZi7FTYFzufKzRZyYl3zm+KHygpGgnli8mDBXWvz30QRFF+Vv6ktYFZFqtD67XSu7tDIdCSQfkzvZ2zoo02Adyew1tKSmIaBXNGGNgdTc8CGaVENswuERgJGmabu17nmFoZIJhzUed0bJwJEWZdNmoK4U9vha4MAemuyCJIRDN/uDq6R2st2nh1+VnnWOFFGo3bDgI00pD+6UYUPdvyDasVQQFclTHTRqd9ZGOz0UVP0MsDF1+krUCOHLERpwIjD6yG2z6UlKjf1PajdJ2USHVlegh5p1Go2arz/9wMNSM0FygMuIku6gvl8OzQjDAnWSnFVCPRYRTf7REQKm2OBXxWAmmig4OUIiOGlqA4nNWpvfmT2BVN+BUbTJrYSJtyptDQLMW2qzIec=
install:
- cp config/api-common.env config/api.env
- echo "TMDB_API_KEY=$TMDB_API_KEY" >> config/api.env
- cp config/database-common.env config/database.env
- docker-compose build
- docker-compose up -d
script:
- until docker-compose exec database psql "$POSTGRES_URI" -c "select 1" > /dev/null
  2>&1; do sleep 2; done
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/ml-tv/tv-api && make
  migration"
- docker-compose exec api /bin/bash -ic "cd /go/src/github.com/ml-tv/tv-api/src &&
  go test ./..."
deploy:
- provider: script
  on: staging
  skip_cleanup: true
  script: ./deploy_staging.sh
notifications:
  email:
    recipients:
      secure: OalMK7QSZmKRoGckdxnc71XoB8hSw2kzncuAsBkaa3tMGNsBUP/NRTNAOTVu7krXdyh9kze+nlxULnLAkK82OaBkLEbsTecZ7jixwgRt/A2TXswxWxFdMUw+z6xVi7tieyXETQsUpjCrhweV+pdZxlvN0RAvg9yHluX/vq9u/ScH1qqWT4v/L6oDRnPD2FBPQIl4hr12nFCupcDjNIm8Lx6UfXANOmjSlXl5GGE5LxqjRinkbeYNIRhjFctjHUH6s9g4WlM0+/9iM/d3reCWs7emYzVvxZHIVf8GmbDXXhv425wPS97C5cpwo0MHxh3EAAbCFVkLPD3LYivULR4ZGFn0F/GzGP51F19bSeDwwFTRjD3hf5FCZ7nLXAKbuqQuvGbz8DMxw+xhwBTElRfph88K0MAqAlvjh8s919FnYJ93iDvyVSPcvoSV8+ilBxB5oejGxb2cIBigIIXNVr6FaSI5IkFDzCWfnwlD/qjUYmR1N0qYKca5xK7VpLU2VcERH/kMQSFCQFOVqkxmxF+/YPAkK0myYonPspKy5F+2t7aywdhv0jA79/ezUHKeK1MkmPmxjmNZFIESR0zKHGGh8eTYZPG/wp2TahxIGk6fMNQ7R6+cUqskgt5r/CPBl3SDAHMMlZuiuDvxlXKVSNuISPw/OZ41qi39tksQtNho+Sk=
    on_success: change
    on_failure: always
